### ISSUE TITLE
fix path and locations of static files 

### ISSUE THREAD

**Issue by nextel** [FuJT/insaneTrack#6]
Now our application  looks like in the attached picture, this is because there are broken links in the html file.
![screenshot from 2017-02-05 21-29-03](https://cloud.githubusercontent.com/assets/628765/22628747/f6aec5e6-ebf2-11e6-8052-ef350f3c5493.png)

**Comment by WaNgeL-SaTaR** [comment]
![9000](https://cloud.githubusercontent.com/assets/1074859/25307293/0f303cae-27a7-11e7-903e-cfed3669bbf3.png)
